version: '3.9'

services:
  # Python backend
  pybackend:
    build:
      context: .
      dockerfile: docker/pybackend.Dockerfile
    environment:
      PORT: 3000
    volumes:
      - made-data:/app/.made
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - pybackend
    ports:
      - "8080:80"

volumes:
  made-data:
